package com.stevenfrew.beatprompter.events

object Events {
	private const val HANDLER_MESSAGE_BASE_ID = 1834739585

	const val BLUETOOTH_CHOOSE_SONG = HANDLER_MESSAGE_BASE_ID
	const val BLUETOOTH_TOGGLE_START_STOP = HANDLER_MESSAGE_BASE_ID + 1
	const val BLUETOOTH_SET_SONG_TIME = HANDLER_MESSAGE_BASE_ID + 2
	const val MIDI_START_SONG = HANDLER_MESSAGE_BASE_ID + 3
	const val MIDI_CONTINUE_SONG = HANDLER_MESSAGE_BASE_ID + 4
	const val MIDI_STOP_SONG = HANDLER_MESSAGE_BASE_ID + 5
	const val END_SONG = HANDLER_MESSAGE_BASE_ID + 6
	const val CLOUD_SYNC_ERROR = HANDLER_MESSAGE_BASE_ID + 7
	const val FOLDER_CONTENTS_FETCHING = HANDLER_MESSAGE_BASE_ID + 8
	const val FOLDER_CONTENTS_FETCHED = HANDLER_MESSAGE_BASE_ID + 9
	const val CONNECTION_ADDED = HANDLER_MESSAGE_BASE_ID + 10
	const val MIDI_SONG_SELECT = HANDLER_MESSAGE_BASE_ID + 11
	const val MIDI_PROGRAM_CHANGE = HANDLER_MESSAGE_BASE_ID + 12
	const val SONG_LOAD_CANCELLED = HANDLER_MESSAGE_BASE_ID + 13
	const val SONG_LOAD_FAILED = HANDLER_MESSAGE_BASE_ID + 14
	const val CONNECTION_LOST = HANDLER_MESSAGE_BASE_ID + 15
	const val SONG_LOAD_LINE_PROCESSED = HANDLER_MESSAGE_BASE_ID + 16
	const val SONG_LOAD_COMPLETED = HANDLER_MESSAGE_BASE_ID + 17
	const val MIDI_SET_SONG_POSITION = HANDLER_MESSAGE_BASE_ID + 18
	const val CACHE_UPDATED = HANDLER_MESSAGE_BASE_ID + 19
	const val PERMISSIONS_UPDATED = HANDLER_MESSAGE_BASE_ID + 20
	const val CLEAR_CACHE = HANDLER_MESSAGE_BASE_ID + 21
	const val BLUETOOTH_PAUSE_ON_SCROLL_START = HANDLER_MESSAGE_BASE_ID + 22
	const val BLUETOOTH_QUIT_SONG = HANDLER_MESSAGE_BASE_ID + 23
	const val ENABLE_STORAGE = HANDLER_MESSAGE_BASE_ID + 24
	const val ENABLE_BLUETOOTH = HANDLER_MESSAGE_BASE_ID + 25
	const val CACHE_CLEARED = HANDLER_MESSAGE_BASE_ID + 26
	const val TEMPORARY_SET_LIST_CLEARED = HANDLER_MESSAGE_BASE_ID + 27
	const val DATABASE_READ_ERROR = HANDLER_MESSAGE_BASE_ID + 28
	const val DATABASE_WRITE_ERROR = HANDLER_MESSAGE_BASE_ID + 29
}